const breadShopDetailComment = {
  SET_SHOP_DETAIL_COMMENT: 'SET_SHOP_DETAIL_COMMENT', // 댓글 리스트 저장 타입
  SET_SHOP_DETAIL_COMMENT_MORE: 'SET_SHOP_DETAIL_COMMENT_MORE',
  SET_DETAIL_COMMENT_REGISTER: 'SET_DETAIL_COMMENT_REGISTER',
  SET_COMMENT_MODIFY: 'SET_COMMENT_MODIFY',
  SET_COMMNET_DELETE: 'SET_COMMNET_DELETE',
  SET_RECOMMENT_REGISTER: 'SET_RECOMMENT_REGISTER',
  SET_RECOMMENT_MODIFY: 'SET_RECOMMENT_MODIFY',
  SET_RECOMMENT_DELETE: 'SET_RECOMMENT_DELETE'
};

export default breadShopDetailComment;
