const breadShopDetailComment = {
  SET_SHOP_DETAIL_COMMENT: 'SET_SHOP_DETAIL_COMMENT',
  SET_DETAIL_COMMENT_REGISTER: 'SET_DETAIL_COMMENT_REGISTER',
  SET_COMMENT_MODIFY: 'SET_COMMENT_MODIFY',
  SET_COMMNET_DELETE: 'SET_COMMNET_DELETE',

  // 대댓글
  SET_RECOMMENT_REGISTER: 'SET_RECOMMENT_REGISTER',
  SET_RECOMMENT_MODIFY: 'SET_RECOMMENT_MODIFY',
  SET_RECOMMENT_DELETE: 'SET_RECOMMENT_DELETE'
};

export default breadShopDetailComment;
