const breadShopDetailComment = {
  SET_SHOP_DETAIL_COMMENT: 'SET_SHOP_DETAIL_COMMENT',
  SET_DETAIL_COMMENT_REGISTER: 'SET_DETAIL_COMMENT_REGISTER',
  SET_COMMENT_MODIFY: 'SET_COMMENT_MODIFY',
  SET_COMMNET_DELETE: 'SET_COMMNET_DELETE'
};

export default breadShopDetailComment;
