const breadShopDetailComment = {
  SET_SHOP_DETAIL_COMMENT: 'SET_SHOP_DETAIL_COMMENT', // 댓글 리스트 저장 타입
  SET_SHOP_DETAIL_COMMENT_MORE: 'SET_SHOP_DETAIL_COMMENT_MORE', // 댓글 pagination 타입
  SET_DETAIL_COMMENT_REGISTER: 'SET_DETAIL_COMMENT_REGISTER', // 댓글 등록 타입
  SET_COMMENT_MODIFY: 'SET_COMMENT_MODIFY', // 댓글 수정 타입
  SET_COMMNET_DELETE: 'SET_COMMNET_DELETE', // 댓글 삭제 타입
  SET_RECOMMENT_REGISTER: 'SET_RECOMMENT_REGISTER', // 대댓글 등록 타입
  SET_RECOMMENT_MODIFY: 'SET_RECOMMENT_MODIFY', // 대댓글 수정 타입
  SET_RECOMMENT_DELETE: 'SET_RECOMMENT_DELETE' // 대댓글 삭제 타입
};

export default breadShopDetailComment;
