const breadShopReview = {
  SET_BREAD_SHOP_REVIEW: 'SET_BREAD_SHOP_REVIEW',
  SET_SHOP_REVIEW_WRITING: 'SET_SHOP_REVIEW_WRITING',
  SET_SHOP_REVIEW_DELETE: 'SET_SHOP_REVIEW_DELETE',
  SET_SHOP_REVIEW_MODIFY: 'SET_SHOP_REVIEW_MODIFY'
};

export default breadShopReview;
