const breadTypes = {
  BREAD_LIST_SET: 'BREAD_LIST_SET',
  BREAD_LIST_MORE: 'BREAD_LIST_MORE',
  HEART_LIKE_TRUE: 'HEART_LIKE_TRUE',
  HEART_LIKE_FALSE: 'HEART_LIKE_FALSE',
  SET_BREAD_RESET: 'SET_BREAD_RESET'
};

export default breadTypes;
