const breadTypes = {
  BREAD_LIST_SET: 'BREAD_LIST_SET',
  BREAD_LIST_MORE: 'BREAD_LIST_MORE',
  HEART_LIKE_TRUE: 'HEART_LIKE_TRUE',
  HEART_LIKE_FALSE: 'HEART_LIKE_FALSE'
};

export default breadTypes;
