const breadShopTypes = {
  SET_BREAD_SHOP_LIST: 'SET_BREAD_SHOP_LIST',
  HEART_LIKE_TRUE: 'HEART_LIKE_TRUE',
  HEART_LIKE_FALSE: 'HEART_LIKE_FALSE',
  SET_ADDRESS_SI: 'SET_ADDRESS_SI'
};

export default breadShopTypes;
